In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [48]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9165275459098498

In [17]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9833333333333333

In [11]:
rfm = RandomForestClassifier()
rfm.fit(X_train, y_train)
rfm.score(X_test, y_test)

0.9703703703703703

In [30]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [31]:
for train_index, test_index in kf.split([i for i in range(10)]):
    print(train_index, test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [24]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [26]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9833333333333333

In [27]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [49]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [33]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [34]:
scores_rf

[0.9398998330550918, 0.9565943238731218, 0.9181969949916527]

In [35]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [36]:
from sklearn.model_selection import cross_val_score

In [51]:
cross_val_score(LogisticRegression(max_iter = 10000), digits.data, digits.target, cv = 3)

array([0.92487479, 0.93989983, 0.92320534])

In [39]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [40]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.925     , 0.91666667, 0.95821727, 0.96100279, 0.93593315])

In [41]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.85      , 0.82222222, 0.89415042, 0.88579387, 0.85793872])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target)

array([0.91944444, 0.91944444, 0.94150418, 0.94428969, 0.91922006])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target)

array([0.93055556, 0.90277778, 0.94707521, 0.95543175, 0.91364903])

In [45]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.91666667, 0.88333333, 0.96100279, 0.96100279, 0.92200557])

In [1]:
import numpy


RuntimeError: The current Numpy installation ('c:\\users\\divyaranjan parida\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86