In [1]:
import pandas as pd 
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [2]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('flower', axis = 'columns'), iris.target, test_size = 0.3)

In [10]:
from sklearn.svm import SVC
model = SVC(C = 1, gamma = 'auto')
model.fit(X_train, y_train)

SVC(C=1, gamma='auto')

In [11]:
model.score(X_test, y_test)

1.0

In [14]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel = 'linear', C = 1, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [15]:
cross_val_score(SVC(kernel = 'rbf', C = 1), iris.data, iris.target, cv = 5)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [20]:
cross_val_score(SVC(kernel = 'linear', C = 0.5, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 1.        , 0.96666667, 1.        ])

In [21]:
cross_val_score(SVC(kernel = 'rbf', C = 0.5, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [23]:
import numpy as np
kernels = ['rbf', 'linear']
C = [1, 10, 20]
avg_score = {}
for i in kernels:
    for j in C:
        cv_scores = cross_val_score(SVC(kernel = i, C = j), iris.data, iris.target, cv = 5)
        avg_score[i+"-"+str(j)] = np.average(cv_scores)
        
avg_score

{'rbf-1': 0.9666666666666666,
 'rbf-10': 0.9800000000000001,
 'rbf-20': 0.9800000000000001,
 'linear-1': 0.9800000000000001,
 'linear-10': 0.9733333333333334,
 'linear-20': 0.9666666666666666}

In [24]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma = 'auto'), {
    'C':[1,10,20],
    'kernel':['rbf', 'linear']
}, cv = 5, return_train_score = False)

In [25]:
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00159588, 0.00106649, 0.00128331, 0.00111728, 0.00155239,
        0.00179238]),
 'std_fit_time': array([3.43794419e-04, 5.15624813e-05, 7.75263901e-05, 9.75699481e-05,
        5.07641730e-04, 4.22938335e-04]),
 'mean_score_time': array([0.00068378, 0.00051799, 0.00056243, 0.00052996, 0.00083013,
        0.00090284]),
 'std_score_time': array([1.40464524e-04, 2.59101219e-05, 1.50487269e-05, 2.91890561e-05,
        3.12932914e-04, 2.54875568e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [26]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001596      0.000344         0.000684        0.000140       1   
1       0.001066      0.000052         0.000518        0.000026       1   
2       0.001283      0.000078         0.000562        0.000015      10   
3       0.001117      0.000098         0.000530        0.000029      10   
4       0.001552      0.000508         0.000830        0.000313      20   
5       0.001792      0.000423         0.000903        0.000255      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [28]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [29]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multi

In [30]:
clf.best_score_

0.9800000000000001

In [31]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [36]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma = 'auto'), {
        'C': [1,10,20],
        'kernel': ['rbf', 'linear']
    },
    cv = 5, 
    return_train_score = False, 
    n_iter = 2
)
rs.fit(iris.data, iris.target)
pd.Dataframe(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [37]:
rs.cv_results_

{'mean_fit_time': array([0.00140696, 0.00114355]),
 'std_fit_time': array([0.00018933, 0.00011877]),
 'mean_score_time': array([0.00074306, 0.00062461]),
 'std_score_time': array([0.00011743, 0.00011659]),
 'param_kernel': masked_array(data=['rbf', 'linear'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[1, 1],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 1}, {'kernel': 'linear', 'C': 1}],
 'split0_test_score': array([0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.98, 0.98]),
 'std_test_score': array([0.01632993, 0.01632993]),
 'rank_test_score': array([1, 1], dtype=int32)}

In [38]:
dir(rs)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multi